name: Code Coverage

on:
  pull_request:

env:
  JAVA_VERSION: 11
  FLUTTER_VERSION: '3.10.6'
  FLUTTER_CHANNEL: 'stable'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Install dependencies
        run: flutter pub get

      - name: Generate test files
        run: | 
          chmod +x ./coverage.sh
          ./coverage.sh

      - name: Unit Tests
        run: flutter test --coverage
      
      - name: Install lcov
        run: sudo apt-get install -y lcov
      
      - name: Remove generated files from code coverage report
        run: lcov --remove coverage/lcov.info 'lib/*/*.freezed.dart' 'lib/*/*.g.dart' 'lib/*/*.part.dart' 'lib/generated/*.dart' 'lib/generated/*/*.dart' o coverage/lcov.info
      
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
          flags: unittests
      
      - name: Delete helper test files
        run: rm -rf test/coverage_helper_test.dart